#! /bin/sh
xsetroot -cursor_name left_ptr
killall redshift compton feh sxhkd

xsetroot -cursor_name left_ptr

# key bindings
sxhkd &
# wallpaper
feh --no-fehbg --bg-scale ~/Pictures/Wallpapers/PixelArt.jpg &
# panel
exec ~/.config/polybar/launch.sh &
# start redshift
exec redhift &

# start compton
compton --config ~/.config/compton/compton.conf &

bspc config focused_border_color "#2979ff"
bspc config normal_border_color "#616161"
bspc config active_border_color "#d500f9"
bspc config presel_feedback_color "#388e3c"

## Bspwm configurations
bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'

bspc config border_width 4
bspc config window_gap 4
bspc config top_padding 20
bspc config right_padding 2
bspc config bottom_padding 2
bspc config left_padding 2
bspc config border_radius 5

bspc config split_ratio 0.5
bspc config boarderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod1
bspc config click_to_focus true
bspc config focus_follows_pointer true

# Window Rules
